version: 2
jobs:
  build:
    docker:
      - image: kivy/buildozer

    working_directory: ~/repo

    steps:
      - run:
          name: checkout
          command: |
            git clone https://github.com/tshirtman/kivy_service_osc.git .
            echo "checking out $CIRCLE_SHA1"
            git checkout ${CIRCLE_SHA1}
            git rev-parse HEAD

      # Download and cache dependencies
      - restore_cache:
          keys:
            - buildozer-home-2-{{ checksum "buildozer.spec" }}
            # fallback to using the latest cache if no exact match is found

      - run:
          name: build
          command: |
            buildozer android debug

      - save_cache:
          paths:
            - .buildozer
            - ~/.buildozer
          key: buildozer-home-{{ checksum "buildozer.spec" }}

      - store_artifacts:
          path: bin/
          destination: bin/
